<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JSON Data Viewer</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h1 class="text-center mb-4">APK Files with SHA256</h1>
        <div id="json-table" class="table-responsive"></div>
    </div>

    <script>
        // Fetch the JSON data from the links.json file
        fetch('links.json')
            .then(response => response.json())
            .then(data => {
                const jsonTable = document.getElementById('json-table');
                let tableHTML = '';

                // Loop through the JSON data to build table rows
                Object.keys(data).forEach(version => {
                    // Add a version heading
                    tableHTML += `<h2>${version}</h2>`;
                    
                    // Create the table for each version
                    tableHTML += `<table class="table table-bordered table-striped">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th>Name</th>
                                            <th>Link</th>
                                            <th>SHA256</th>
                                        </tr>
                                    </thead>
                                    <tbody>`;

                    data[version].forEach(item => {
                        tableHTML += `<tr>
                                        <td>${item.name}</td>
                                        <td><a href="${item.link}" target="_blank">Download</a></td>
                                        <td>${item.sha256}</td>
                                    </tr>`;
                    });

                    tableHTML += `</tbody></table>`;
                });

                jsonTable.innerHTML = tableHTML;
            })
            .catch(error => {
                console.error('Error loading the JSON file:', error);
            });
    </script>
</body>
</html>
