name: Update APK Index

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "Enter the filename"
        required: true
      sha256:
        description: "Enter the SHA256 hash"
        required: true

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Process User Input
        id: process_input
        run: |
          # Extract inputs
          FILENAME="${{ github.event.inputs.filename }}"
          SHA256="${{ github.event.inputs.sha256 }}"
          
          # Parse version numbers
          MAJOR_MINOR=$(echo "$FILENAME" | grep -oP '^\d+\.\d+')
          THREE_DIGIT=$(echo "$FILENAME" | grep -oP '^\d+\.\d+\.\d+')
          
          # Save them as environment variables
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV
          echo "SHA256=$SHA256" >> $GITHUB_ENV
          echo "MAJOR_MINOR=$MAJOR_MINOR" >> $GITHUB_ENV
          echo "THREE_DIGIT=$THREE_DIGIT" >> $GITHUB_ENV

      - name: Update index.html Chronologically
        run: |
          # Prepare the hyperlink
          HYPERLINK="<p><a href=\"https://github.com/mcpebd/yssmirror/releases/download/$THREE_DIGIT/$FILENAME\">$FILENAME</a><br><code>SHA256: $SHA256</code></p>"
          
          # Extract the section of the file for the MAJOR_MINOR version
          SECTION_START=$(grep -n "<h2>$MAJOR_MINOR</h2>" index.html | cut -d: -f1)
          SECTION_END=$(tail -n +$((SECTION_START + 1)) index.html | grep -n -m 1 -E "<h2>|</body>" | cut -d: -f1)

          if [[ -z "$SECTION_START" ]]; then
            # Add a new section if it doesn't exist
            sed -i "/<\/body>/i <h2>$MAJOR_MINOR</h2><hr>\n$HYPERLINK" index.html
          else
            # Extract and sort entries
            START_LINE=$((SECTION_START + 1))
            END_LINE=$((START_LINE + SECTION_END - 2))
            awk "NR < $START_LINE || NR > $END_LINE" index.html > temp.html
            awk "NR >= $START_LINE && NR <= $END_LINE" index.html > temp_section.html

            # Add the new line and sort
            echo "$HYPERLINK" >> temp_section.html
            sort -r -o temp_section.html temp_section.html  # Sort in reverse order

            # Recombine the file
            cat temp.html temp_section.html > index.html
          fi

      - name: Commit Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Update index.html with new APK $FILENAME"
          git push
