name: Update APK Index

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "Enter the filename"
        required: true
      sha256:
        description: "Enter the SHA256 hash"
        required: true

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Process User Input
        id: process_input
        run: |
          # Extract inputs
          FILENAME="${{ github.event.inputs.filename }}"
          SHA256="${{ github.event.inputs.sha256 }}"
          
          # Parse version numbers
          MAJOR_MINOR=$(echo "$FILENAME" | grep -oP '^\d+\.\d+')
          THREE_DIGIT=$(echo "$FILENAME" | grep -oP '^\d+\.\d+\.\d+')
          
          # Save them as environment variables
          echo "FILENAME=$FILENAME" >> $GITHUB_ENV
          echo "SHA256=$SHA256" >> $GITHUB_ENV
          echo "MAJOR_MINOR=$MAJOR_MINOR" >> $GITHUB_ENV
          echo "THREE_DIGIT=$THREE_DIGIT" >> $GITHUB_ENV

      - name: Update index.html Chronologically
        run: |
          # Prepare the hyperlink
          HYPERLINK="<p><a href=\"https://github.com/mcpebd/yssmirror/releases/download/$THREE_DIGIT/$FILENAME\">$FILENAME</a><br><code>SHA256: $SHA256</code></p>"
          
          # Check if the section for MAJOR_MINOR exists
          if ! grep -q "<h2>$MAJOR_MINOR</h2>" index.html; then
            # Add a new section for the MAJOR_MINOR version
            sed -i "/<h2>[0-9]/i <h2>$MAJOR_MINOR</h2><hr>" index.html
          fi
          
          # Extract the section lines
          SECTION_START=$(grep -n "<h2>$MAJOR_MINOR</h2>" index.html | cut -d: -f1)
          SECTION_END=$(tail -n +$((SECTION_START + 1)) index.html | grep -n -m 1 -E "<h2>|</body>" | cut -d: -f1)

          if [ -z "$SECTION_END" ]; then
            SECTION_END=$(wc -l < index.html)
          else
            SECTION_END=$((SECTION_START + SECTION_END - 1))
          fi
          
          # Extract and insert the hyperlink within the section
          awk "NR < $SECTION_START || NR > $SECTION_END" index.html > temp.html
          awk "NR >= $SECTION_START && NR <= $SECTION_END" index.html > temp_section.html

          if ! echo "$HYPERLINK" | grep -q "$(echo "$HYPERLINK" | grep -oP '\d+\.\d+\.\d+')"; then
            echo "$HYPERLINK" >> temp_section.html
            sort -r -k1.14 temp_section.html -o temp_section.html  # Sort within the section by version number
          fi

          cat temp.html temp_section.html > index.html

      - name: Commit Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Update index.html with new APK $FILENAME"
          git push
