name: Update JSON with APK Data

on:
  workflow_dispatch:
    inputs:
      major:
        description: 'Enter major version (e.g., 1.21)'
        required: true
        type: string
      filename:
        description: 'Enter filename (e.g., 1.21.44.01_arm32_arm64_patched.apk)'
        required: true
        type: string
      link:
        description: 'Enter the download link (e.g., https://github.com/mcpebd/yssmirror/releases/download/1.21.44/1.21.44.01_arm32_arm64_patched.apk)'
        required: true
        type: string
      sha256:
        description: 'Enter the SHA256 hash (e.g., 542fc5d9a997a5c8678e4ada4c40cd916da4db572a0435b69f0023a2efc63dd1)'
        required: true
        type: string

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq

      - name: Update JSON with APK Data
        run: |
          # Define inputs
          major_version="${{ github.event.inputs.major }}"
          filename="${{ github.event.inputs.filename }}"
          link="${{ github.event.inputs.link }}"
          sha256="${{ github.event.inputs.sha256 }}"

          # File to update
          json_file="apk_versions.json"

          # Check if the JSON file exists
          if [ ! -f "$json_file" ]; then
            echo "{}" > "$json_file"
          fi

          # Add new data to JSON using jq
          jq --arg major "$major_version" --arg filename "$filename" --arg link "$link" --arg sha256 "$sha256" \
            '
              .[$major] = [
                {
                  "name": $filename,
                  "link": $link,
                  "sha256": $sha256
                ]
              ]
            ' "$json_file" > tmp.json && mv tmp.json "$json_file"

          # Commit changes back to the repository
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add "$json_file"
          git commit -m "Update JSON with new APK version $major_version"
          git push
