name: Download and Upload with Tag

on:
  workflow_dispatch:
    inputs:
      LINK:
        description: 'The URL to download the file from'
        required: true
        type: string
      TAG:
        description: 'The tag for the release'
        required: true
        type: string

jobs:
  download-and-upload:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up curl and hash
        run: |
          # Set environment variables for inputs
          echo "LINK=${{ github.event.inputs.LINK }}" >> $GITHUB_ENV
          echo "TAG=${{ github.event.inputs.TAG }}" >> $GITHUB_ENV

      - name: Download file using curl
        run: |
          curl -L -O ${{ github.event.inputs.LINK }}

      - name: Run sort.bat with TAG
        run: |
          tree /f
          if exist links.json del /q /s links.json
          .\sort.bat ${{ github.event.inputs.TAG }}

      - name: Calculate SHA256 checksum
        run: |
          $file = (Get-ChildItem *.apk).Name
          $sha256 = Get-FileHash $file -Algorithm SHA256
          $sha256.Hash | Out-File sha256.txt

      - name: Read SHA256 checksum from hash.txt
        run: |
          $sha256sum = Get-Content sha256.txt
          del /q /s sha256.txt
          echo "SHA256: $sha256sum"
          
      - name: Upload release asset to GitHub
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Create release and upload asset
          gh release create ${{ github.event.inputs.TAG }} $(Get-ChildItem *.apk).Name --notes "SHA256sum:\n```$sha256sum\n```"
          del /q /s *.apk

          
      - name: Commit changes and push to repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Add downloaded file and SHA256 checksum"
          git push
